### ISSUE TITLE
pictures not uploading

### ISSUE THREAD

**Issue by webernick79** [osu-cascades/bda-explorer#104]
@ybakos gotten some feedback that pictures aren't uploading in production site? I'm doing some testing? but we should get this sorted pretty quick.

**Comment by webernick79** [comment]
I can't duplicate the error in production or locally?

**Comment by ybakos** [comment]
@webernick79 So is this not a bug?

**Comment by webernick79** [comment]
@ybakos , guess not, I tried a bunch of image extensions, etc.....and couldn't make it happen.
