### ISSUE TITLE
Add Disqus comments on project views

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#106]
From: Julie Vanderwal <XXX>
Subject: Re: BDA website
Date: October 22, 2018 at 3:58:02 PM PDT

...

**I love the idea of a chat room or other means for interactive discussion** -- but in the meantime, would it be possible to add static text fields for sharing about how the project is working -- e.g. objectives attained, lessons learned -- as well as additional project photos? Also, where might I add the project url?

**Comment by cooperphyz** [comment]
Implemented Disqus for our chat implementation on each individual project now. We'll see how our client receives it.
