### ISSUE TITLE
Project: Additional photos

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#108]
From: Julie Vanderwal <XXX>
Subject: Re: BDA website
Date: October 22, 2018 at 3:58:02 PM PDT

...

Did Matt also pass along my other questions? I love the idea of a chat room or other means for interactive discussion -- but in the meantime, would it be possible to add static text fields for sharing about how the project is working -- e.g. objectives attained, lessons learned -- **as well as additional project photos**? Also, where might I add the project url?

**Comment by nueadkie** [comment]
Closed with PR #195
