### ISSUE TITLE
"/" above nav

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#117]
@ybakos , I've got this little backslash floating around just above the nav. I can't track down what is doiing this? Any chance you could have a look?

![Screen Shot 2020-05-15 at 8 32 33 AM](https://user-images.githubusercontent.com/34071692/82068520-f1848780-9686-11ea-808e-123174b87fe0.png)

**Comment by teemal** [comment]
@nick4rivers Just a heads up, I'm unable to reproduce this on Chrome, Brave, or Firefox. Also looking at `_nav.html.erb` and `application.html.erb`, I don't see anything that would cause a rogue forward slash.

**Comment by teemal** [comment]
![image](https://user-images.githubusercontent.com/26888205/82080502-87c1a900-9699-11ea-8055-962f6896e708.png)

**Comment by nick4rivers** [comment]
Hmmmm.... @teemal thanks a ton for looking.... It isn't on the site that is the production build. You should see it on the staging build: https://bda-explorer-staging.herokuapp.com/

Also, it doesn't look like whatever you have cloned is up to date with the master branch?

Again, really appreciate you looking

**Comment by teemal** [comment]
Was just about to update my comment because I realized I was probably looking on the wrong branch lol. Is development what is pushed to staging?

**Comment by nick4rivers** [comment]
@teemal, I've just been pushing everything to `master`, and that is what was pushed to staging.

**Comment by teemal** [comment]
I could be entirely wrong but I might have found it. Looked for everything I can think of and couldn't really find anything creating a rogue slash or any non-escaped slashes. You're getting a warning for the `gon` gem and might have gotten lucky, though. I think in your link to your leaflet styling, there is an included slash between the opening and closing of the link like so `<link href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" rel="stylesheet" crossorigin="anonymous">/</link>` . Found [here](https://github.com/osu-cascades/bda-explorer/blob/c912a0118764f1e1b917a33ca23c6a48978b9330/app/views/layouts/application.html.erb) on line 10

**Comment by nick4rivers** [comment]
Nicely done!!! Thanks a ton @teemal . that fixed it and I'll push it up soon!! Really appreciate the help!!

**Comment by teemal** [comment]
Nice! Glad that worked out!
