### ISSUE TITLE
Feature: Integration of search libraries for location

### ISSUE THREAD

**Issue by cooperphyz** [osu-cascades/bda-explorer#149]
Currently, the only way to select a location on the map is to manually enter LAT/LONG coordinates. Nick Weber requested implementation of the map marker dragging functionality, as well as being able to search location to retrieve coordinates. A user would be able to enter a location to receive coordinates, instead of entering coordinates or dragging a map marker.

**Comment by nueadkie** [comment]
Issue was resolved with PR #172.
