### ISSUE TITLE
Minor Landing Page Updates

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#167]
Hey @cooperphyz and @nueadkie 

Couple minor suggestions on the landing page. Nothing urgent but add and ask questions if needed. Just see my screenshot for ideas.

You might also think about adding another card for "total number of organizations" which we will have soon.

<img width="1238" alt="Screen Shot 2021-11-11 at 2 34 02 PM" src="https://user-images.githubusercontent.com/34071692/141381642-ad40dca3-3d27-4879-9bc9-656683979a7d.png">

**Comment by cooperphyz** [comment]
Tinkered around with the changes you had suggested. Removing the block of headers above the stat cards was definitely the right call. Will add in the affiliations card once that is up and running as well. 

![image](https://user-images.githubusercontent.com/43557147/141527834-abe4c5eb-6f00-4e59-a4eb-40a7f54f69c1.png)

**Comment by nick4rivers** [comment]
Perfect - much cleaner! I'll put on my To Do list to get you some about page content later this week.
