### ISSUE TITLE
Password Retrieval not working

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#174]
Forgotten password retrieval not working. 
![preview-chat-image](https://user-images.githubusercontent.com/34071692/147962132-c323840a-caba-4bb8-8b9f-21bc988b644a.png)

**Comment by ybakos** [comment]
Just chiming in here. The error is due to a change in gmail's rules for use of their SMTP servers. @nueadkie and @cooperphyz , we'll need to use the google account to create an "application password" and use those credentials in the production configuration. I can assist.

**Comment by cooperphyz** [comment]
Fixed awhile ago by Yong, working properly now.
