### ISSUE TITLE
Upgrade to latest Rails 7.0.x 

### ISSUE THREAD

**Issue by nueadkie** [osu-cascades/bda-explorer#198]
A new major version of Rails was released recently, while the website is still running on Rails 5.2.6. Upgrading may fix a bug regarding ActiveStorage where all of a project's photos must be deleted when form validation fails.

**Comment by ybakos** [comment]
Also bump to Ruby 3.1.2 while you're at it.

**Comment by nueadkie** [comment]
Pushed into development with #199 and into master with #252
