### ISSUE TITLE
Affiliations: request to url raises exception instead of saying 'You need to sign in or sign up before continuing.'

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#223]
When a user **is signed in** and they try to visit an affiliations URL, the app displays a nice flash saying "you must own the project".

But when a user is not signed in, and tries to access http://bda-explorer.herokuapp.com/projects/179/affiliations for example, an exception is raised.

Ensure that the right access control in the controller is declared.

**Comment by cooperphyz** [comment]
Issue has been fixed with most recent iteration. User is now authenticated when accessing the affiliations page, fixing the issue.
