### ISSUE TITLE
Add Photos on Project Edit

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#243]
Could we consider moving the Upload Photos widget and box to be closer to the existing photos so that it is easier to find.

![Screen Shot 2022-04-15 at 9 07 20 AM](https://user-images.githubusercontent.com/34071692/163594013-08c50de3-8c78-435b-8ac6-535bbb4cdb25.png)

**Comment by nueadkie** [comment]
Resolved with #250
