### ISSUE TITLE
Simplify List View Organizations

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#245]
I think the list view is getting too busy given the number of organizations on each project. Could you just change the organizations to be a , seperated string. e.g., Anabranch Solutions, NOAA Fisheries, Etc......

![Screen Shot 2022-04-15 at 10 58 17 AM](https://user-images.githubusercontent.com/34071692/163605308-8ca7a976-c7ff-4447-8b97-14417e484166.png)

**Comment by nick4rivers** [comment]
You might even consider truncating the concatenated string at a certain number of characters......

**Comment by nick4rivers** [comment]
@cooperphyz example


![Screen Shot 2022-05-12 at 1 48 28 PM](https://user-images.githubusercontent.com/34071692/168165499-4eec4df2-7d6a-44c8-b256-427ef0141cdc.png)

**Comment by cooperphyz** [comment]
Changes live on production now
