### ISSUE TITLE
Landing Page Card Text

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#246]
Hey - some small changes to text....

- Replace "BDA-Explorer" with "LTPBR Explorer"
- Change text on several of the cards.

![Screen Shot 2022-04-15 at 11 26 05 AM](https://user-images.githubusercontent.com/34071692/163607988-5e76b9d7-0c9f-4723-a7bd-9df1c22bec75.png)

**Comment by cooperphyz** [comment]
Fixed up with most recent change
