### ISSUE TITLE
Project URL

### ISSUE THREAD

**Issue by nick4rivers** [osu-cascades/bda-explorer#247]
Rework the "project url" so that it just displays as a link and doesn't actually show the URL. Also should be hidden if no URL is added.

<img width="926" alt="Screen Shot 2022-04-18 at 11 08 23 AM" src="https://user-images.githubusercontent.com/34071692/163853634-03ba0567-aeed-47ca-8c89-e5c9c14a8576.png">

**Comment by cooperphyz** [comment]
Has been shortened down now to just 'Link' with a little arrow. Arrow may or may not be removed in future.
