### ISSUE TITLE
Enhancement: Fix issues with Organizations list

### ISSUE THREAD

**Issue by cooperphyz** [osu-cascades/bda-explorer#263]
Organizations list has several issues, largely pertaining to the link and contact information. Similar issue persists with the link on the project page.

**Comment by nick4rivers** [comment]
@cooperphyz let me know if you have questions about how to finalize this.

**Comment by cooperphyz** [comment]
Has been fixed with last push to production. Contact is removed, and website is shortened to a clickable link.
