### ISSUE TITLE
Upgrade to latest Rails 5.2.x

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#68]

**Comment by ybakos** [comment]
@webernick79 FYI I'm working on upgrading the Rails gem to 5.2.1 (latest). This entails a handful of config changes. I'll let you know when this is done, as you'll need to `bundle install`.

**Comment by ybakos** [comment]
@webernick79 It's done. You may need to do a `bundle install` and/or `bundle update`.

I've deployed this to staging too - but not prod.

**Comment by webernick79** [comment]
Right on @ybakos , thanks for giving this some attention
