### ISSUE TITLE
Projects-map broken

### ISSUE THREAD

**Issue by webernick79** [osu-cascades/bda-explorer#72]
Currently getting this message when I attempt to visit the map page:
![projects-map](https://user-images.githubusercontent.com/34071692/45563228-963f2980-b801-11e8-973f-f9b31d9073b4.jpeg)

**Comment by webernick79** [comment]
@ybakos , seems like this is also happening on the project#show view as well

**Comment by ybakos** [comment]
https://stackoverflow.com/questions/31170055/activerecord-postgis-adapter-undefined-method-point-for-nilnilclass/31170056#31170056

Undefined method `point' for nil:NilClass

It's an RGeo thing. Fix the staging & prod config.

**Comment by webernick79** [comment]
Hey @ybakos , I was able to get this fixed on my local setup with this: https://stackoverflow.com/questions/31170055/activerecord-postgis-adapter-undefined-method-point-for-nilnilclass/31170056#31170056

**Comment by ybakos** [comment]
@webernick79 Yep, that's it. Just need to figure out Heroku - will get to it this afternoon.

**Comment by webernick79** [comment]
@ybakos could this work? https://github.com/cyberdelia/heroku-geo-buildpack/

**Comment by webernick79** [comment]
@ybakos or maybe this one: https://github.com/diowa/heroku-buildpack-rgeo-prep

**Comment by ybakos** [comment]
@webernick79 Staging and production are working again.

Something must have happened with the rgeo gem build being broken. The apps on Heroku both had the appropriate buildpacks already (they used to be working).

I flushed the gem caches on Heroku, removed the buildpacks, and deployed from scratch, but using the "Aptfile" approach with the official heroku-buildpack-apt. Basically just followed this one:

https://www.diowa.com/blog/heroku/2017/08/01/using-rgeo-with-geos-on-heroku-with-apt-get

I'm going to add this blog post to Basecamp.

**Comment by ybakos** [comment]
https://github.com/osu-cascades/bda-explorer/commit/59050c95435455f698e496f5d63a7595afac3c72

**Comment by webernick79** [comment]
Thanks a ton @ybakos . Much appreciated, and good reference going forward.
