### ISSUE TITLE
Project: missing validators

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#90]
@webernick79 Consider what fields are required (eg "project name") and be sure there's a validator in `project.rb`. For bonus points, update the project_spec tests.

**Comment by ybakos** [comment]
@webernick79 Take a look at _db/schema.rb_. Which fields should be required that do not show the `null: false` attribute? (eg `narrative`).

Do we want to make narrative, length, number_of_structures, structure_description, or watershed required?

**Comment by webernick79** [comment]
@ybakos  let's make all these required
