### ISSUE TITLE
User: Add name

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/bda-explorer#96]

**Comment by ybakos** [comment]
This was retrofitted to an old migration:

See 31431e287c793e00c2b05110b612ca1f2a963c90

@webernick79 Just to clarify, in Rails, you should "never" alter past migrations.

**Comment by ybakos** [comment]
And never manually modify schema.rb.

**Comment by webernick79** [comment]
Thanks @ybakos ! I really appreciate the tips!

**Comment by ybakos** [comment]
@webernick79 This is done. I also re-aligned the migrations and schema.rb, and both staging/prod databases are in order. For your dev env, I recommend doing:

`rails db:reset`

This will drop and restore your local db.
